CREATE DATABASE IF NOT EXISTS idle_game;
USE idle_game;

-- ユーザーテーブル
CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    device_id CHAR(36) NOT NULL UNIQUE,

    user_name VARCHAR(50),

    level INT NOT NULL DEFAULT 1,
    exp BIGINT NOT NULL DEFAULT 0,

    attack_up INT NOT NULL DEFAULT 0,
    speed_up INT NOT NULL DEFAULT 0,

    is_idle BOOLEAN NOT NULL DEFAULT FALSE,
    idle_started_at DATETIME NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);